project:
  type: website
#  resources:

website:
  title: "explorations, experiments, excitement"
  description: "A blog by Jessica Hoehner"
 #  site-url: [add here]
  repo-subdir: https://github.com/jessmhoehner/jblog
  open-graph: true
  search: true
  reader-mode: true

  navbar:
    title: false
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: index.xml
        text: RSS
    right:
      - text: Sites
      - icon: github
        menu:
        - text: GitHub landing page
            url: https://github.com/jessmhoehner
         - text: blog Source Code
            url: https://github.com/jessmhoehner/jblog
      - href: https://orcid.org/0000-0002-9536-8961
         text: Publications
      - href: https://www.linkedin.com/in/jessmhoehner/
         text: LinkedIn
 page-footer: "Copyright 2024, Jessica Hoehner"
     background: primary
     
 reader-mode: true
 #   center:
     # - href: [add link to blog here]
     #   text: blog

format:
  html:
    theme: minty
    css: styles.css
